---
name: xmodeler-tooling

extra-source-files:
  - alloy/od/template.als

dependencies:
  - base

default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
  - NamedFieldPuns
  - FlexibleContexts

ghc-options:
  - -Wall
  - -Widentities
  - -Werror

library:
  source-dirs: src
  exposed-modules:
    - Modelling.MLM.ToXModeler
    - Modelling.MLM.Config
    - Modelling.MLM.Types
    - Modelling.MLM.Validate
    - Modelling.MLM.Generate
    - Modelling.MLM.FromXModeler
    - Modelling.MLM.Edit
    - Modelling.CdOd.Populate
  dependencies:
    - call-alloy >= 0.4.0.1 && < 0.5
    - exceptions
    - extra
    - file-embed
    - string-interpolate
    - graphviz
    - diagrams-lib
    - diagrams-graphviz
    - parsec
    - containers
    - bimap
    - split
    - Unique
    - text
    - transformers
    - QuickCheck
    - hxt
    - aeson

executables:
  generateRandomMLMs:
    main: generateRandomMLMs.hs
    source-dirs: app
    dependencies:
      - xmodeler-tooling
      - graphviz
      - QuickCheck
      - pretty-simple
  checkValidityOfMLM:
    main: checkValidityOfMLM.hs
    source-dirs: app
    dependencies:
      - xmodeler-tooling
      - pretty-simple
  reLayoutAnMLM:
    main: reLayoutAnMLM.hs
    source-dirs: app
    dependencies:
      - xmodeler-tooling
      - graphviz
  populateAnMLM:
    main: populateAnMLM.hs
    source-dirs: app
    dependencies:
      - xmodeler-tooling
      - graphviz
      - QuickCheck
      - aeson
      - yaml
  useAlloyToPopulateCdOd:
    main: useAlloyToPopulateCdOd.hs
    source-dirs: app
    dependencies:
      - xmodeler-tooling
      - graphviz
      - QuickCheck
      - aeson
      - yaml

tests:
  xmodeler-tooling-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    default-extensions:
      - RecordWildCards
    dependencies:
      - xmodeler-tooling
      - extra
      - graphviz
      - QuickCheck
      - hspec
      - directory
      - filepath
      - pretty-simple
