---
resolver: lts-19.25

packages:
  - .

extra-deps:
  - git: https://github.com/fmidue/modelling-tasks
    commit: 77ab66fc321d823f6712217e11b2a54d161f01ba
  - git: https://github.com/fmidue/output-monad # required for modelling-tasks
    commit: d51169e89ecfc736e12f36732b08d53460c2bb4f
    subdirs:
      - output-monad
  - call-alloy-0.4.0.1 # required for modelling-tasks
  - call-plantuml-0.0.1.1 # required for modelling-tasks
  - hgal-2.0.0.2 # required for modelling-tasks
  - latex-svg-image-0.2 # required for modelling-tasks
  - diagrams-graphviz-1.4.1.1
  - Unique-0.4.7.9

allow-newer: true
